# Generated by Django 3.0.3 on 2020-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='code')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
                ('units', models.FloatField(verbose_name='units')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Department')),
                ('prereq_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Term')),
            ],
            options={
                'ordering': ['-term__year', '-term__half', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseOffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
