# Generated by Django 3.0.3 on 2020-03-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'ordering': ['-term__year', '-term__half', 'course__code']},
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
        ),
    ]
