# Generated by Django 3.0.3 on 2020-03-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_semester'),
        ('course', '0002_auto_20200310_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='student',
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseOffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
