# Generated by Django 3.0.4 on 2020-11-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('assignment', 'Assignment')], max_length=25, verbose_name='post type'),
        ),
    ]
