# Generated by Django 3.0.4 on 2020-11-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Filter', max_length=128, verbose_name='title')),
                ('semesters', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], help_text='<b>Remember course and semester must not be selected at same time</b>', max_length=15, null=True, verbose_name='semesters')),
                ('course', models.ManyToManyField(blank=True, help_text='<b>Remember course and semester must not be selected at same time.</b>', to='course.CourseOffering')),
                ('program', models.ManyToManyField(to='university.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('is_global', models.BooleanField(default=False, help_text='If global is checked announcement filter will not work.', verbose_name='is global')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'University Specific'), (2, 'Program Specifc'), (3, 'Semester Specifc'), (4, 'Course Specifc')], max_length=7, verbose_name='tags')),
                ('announcement_filters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.AnnouncementFilter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tags', '-updated_at'],
            },
        ),
    ]
