# Generated by Django 3.0.3 on 2020-03-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.AnnouncementFilter'),
        ),
    ]
