# Generated by Django 3.0.3 on 2020-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='is draft'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='is global'),
        ),
    ]
