# Generated by Django 3.0.3 on 2020-03-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('announcement', '0002_auto_20200312_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ManyToManyField(to='university.Department')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ManyToManyField(to='announcement.AnnouncementFilter'),
        ),
    ]
