# Generated by Django 3.0.3 on 2020-03-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200310_2356'),
        ('announcement', '0003_auto_20200312_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='department',
            new_name='announcement_filters',
        ),
        migrations.AddField(
            model_name='announcementfilter',
            name='course',
            field=models.ManyToManyField(to='course.CourseOffering'),
        ),
        migrations.AddField(
            model_name='announcementfilter',
            name='types',
            field=models.CharField(choices=[('or', 'Union'), ('and', 'Intersection')], default='or', max_length=3, verbose_name='type'),
        ),
    ]
