# Generated by Django 3.0.3 on 2020-03-12 13:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20200312_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Top'), (2, 'Department Specifc'), (3, 'Semester Specifc'), (4, 'Course Specifc')], max_length=7, verbose_name='tags'),
        ),
    ]
