# Generated by Django 3.0.3 on 2020-03-12 05:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('course', '0002_auto_20200310_2356'),
        ('announcement', '0005_announcementfilter_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementfilter',
            name='semester',
        ),
        migrations.AddField(
            model_name='announcementfilter',
            name='semesters',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], max_length=15, null=True, verbose_name='semesters'),
        ),
        migrations.AlterField(
            model_name='announcementfilter',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='course.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='announcementfilter',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='university.Department'),
        ),
    ]
