# Generated by Django 3.0.3 on 2020-03-13 18:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20200312_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['tags', '-updated_at']},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'University Specific'), (2, 'Department Specifc'), (3, 'Semester Specifc'), (4, 'Course Specifc')], max_length=7, verbose_name='tags'),
        ),
    ]
