# Generated by Django 3.0.3 on 2020-03-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_auto_20200312_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementfilter',
            name='types',
        ),
    ]
