# Generated by Django 3.0.3 on 2020-03-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_remove_announcementfilter_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementfilter',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='title'),
        ),
    ]
