# Generated by Django 3.0.3 on 2020-03-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_announcementfilter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementfilter',
            name='title',
            field=models.CharField(default='Untitled Filter', max_length=128, verbose_name='title'),
        ),
    ]
