# Generated by Django 3.0.3 on 2020-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200310_2356'),
        ('university', '0001_initial'),
        ('announcement', '0010_auto_20200312_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementfilter',
            name='course',
            field=models.ManyToManyField(blank=True, to='course.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='announcementfilter',
            name='department',
            field=models.ManyToManyField(blank=True, to='university.Department'),
        ),
    ]
