# Generated by Django 3.0.3 on 2020-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='display_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='display name'),
        ),
    ]
