# Generated by Django 3.0.3 on 2020-03-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, verbose_name='date of birth'),
        ),
    ]
