# Generated by Django 3.0.3 on 2020-03-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20200310_1808'),
        ('accounts', '0003_auto_20200306_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='BSCS', on_delete=django.db.models.deletion.CASCADE, to='university.Department'),
        ),
    ]
