# Generated by Django 3.0.3 on 2020-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20200310_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=128, verbose_name='description'),
        ),
    ]
