# Generated by Django 3.0.3 on 2020-03-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20200310_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='code'),
        ),
    ]
