# Generated by Django 3.0.3 on 2020-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-year', '-half']},
        ),
        migrations.AlterField(
            model_name='term',
            name='half',
            field=models.IntegerField(choices=[(1, 'Spring'), (2, 'Fall')], max_length=1, verbose_name='half'),
        ),
    ]
