# Generated by Django 3.0.3 on 2020-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20200310_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='half',
            field=models.IntegerField(choices=[(1, 'Spring'), (2, 'Fall')], verbose_name='half'),
        ),
    ]
