# Generated by Django 3.0.4 on 2020-12-04 20:14

from django.db import migrations, models
import django.db.models.deletion
import resources.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseOffering')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceFolder')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to=resources.models.upload_path)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceFolder')),
            ],
        ),
    ]
