# Generated by Django 3.0.4 on 2020-12-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourcesFile',
            new_name='ResourceFile',
        ),
    ]
