# Generated by Django 3.0.4 on 2020-12-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201204_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceFolder'),
        ),
    ]
