# Generated by Django 3.0.4 on 2020-12-04 23:06

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20201204_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='resourcefolder',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
