# Generated by Django 3.0.4 on 2020-12-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20201204_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcefile',
            name='name',
        ),
    ]
