# Generated by Django 3.0.4 on 2020-12-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_resourcefile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceFolder'),
        ),
    ]
