# Generated by Django 3.0.4 on 2020-12-05 01:18

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20201204_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=resources.models.upload_path),
        ),
    ]
